spring:
  application:
    name: message-aggregator
  threads.virual.enabled: true

  profiles:
    active: local

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info

logging:
  file:
    name: logs/application.log
  logback:
    rollingpolicy:
      max-history: 7
      max-file-size: 10MB
  level:
    root: INFO
    com.aggregator: DEBUG
    org.hibernate.SQL: DEBUG

